### ISSUE TITLE
Aeroo Reports not installing in odoo v8 final

### ISSUE THREAD

**Issue by XaRz** [jamotion/aeroo#6]
Hello, 

I can get your code working with latest v8 version. I'm getting:

No module named unohelper
No module named com.sun.star.beans
No module named com.sun.star.uno
No module named com.sun.star.connection
No module named com.sun.star.beans
No module named com.sun.star.lang
No module named com.sun.star.io
No module named com.sun.star.io

Any hints?

**Comment by jordg** [comment]
I have managed to get this working on 6.1. This is probably the same solution for V7/8.
1, Recompile Libreoffice as per https://gist.github.com/hbrunn/6f4a007a6ff7f75c0f8b
2, Note exact version installed. In my case: 1:4.3.5~rc2-0ubuntu1~trusty1
2, Download python-uno_4.3.3-2_amd64.deb
3, Follow instructions to repackage above deb https://gist.github.com/shamil/3140558
    Change:
    Version: 1:4.3.5~rc2-0ubuntu1~trusty1
    Depends: libreoffice-core (= 1:4.3.5~rc2-0ubuntu1~trusty1), .......
4, dpkg-deb -b python-uno python-uno_4.3.5~rc2-0_amd64.deb
5, dpkg -i python-uno_4.3.5~rc2-0_amd64.deb
6, Enjoy

**Comment by lukebranch** [comment]
@jordg ,

Thanks for the heads up, i'll give this a go today for 8.0 and post back here to let you know if it works for 8.0 in 14.04.

**Comment by nagyv** [comment]
Hi,

I've modified @lukebranch's gist to make it run automatically on a pure EC2 m1.medium instance

To build it for yourself, you can follow these steps:
* launch this EC2 instance https://aws.amazon.com/marketplace/pp/B00JV9JBDS at an m1.medium server
* ssh into your instance
* download this gist https://gist.github.com/nagyv/c353b8b8f293a700e30a
* run it & wait (it takes a LOT of time!)
* save your files from /mnt/pyuno/*.deb to your real server / localhost (e.g. scp)

My own build results are here. Use at your own risk.
https://www.dropbox.com/sh/0lzsmc713x9io0t/AAAjY_guZdNL0mrqsrlAZcU_a?dl=0

NB: the last commands in the gist are for installing the just built packages. You might not want to run these on the EC2 instance, but you'll definitely want these to run on your real server.

**Comment by a0c** [comment]
Hi,
Many many thanks to @nagyv and @JurassicPork!

I've successfully installed @nagyv's build results on a fresh Ubuntu 14.04 LTS.
Forked script (although not very useful):
https://gist.github.com/a0c/c8547caa7d28960076fa

Note that I only had to add more libreoffice packages to @nagyv's original script because I've been reinstalling/removing the original LibreOffice installation dozens of times while struggling with aeroo ooo installation.

Test connection from Odoo web-interface works fine now.
Will see how our own aeroo reports are working once 7->8 transition is done.

Once again, many thanks for your help, guys!

**Comment by nagyv** [comment]
Since I've installed aeroo reports, it turned out that this version screws up some qweb-reports. 

On the other hand after installing https://github.com/aeroo/aeroo_reports/ and https://github.com/aeroo/aeroolib everything seems to work well, with just 1 minor modification: get rid of the `report_aeroo_direct_print` if you don't need it, as it has some extra dependencies that you will have to install.

**Comment by rm-jamotion** [comment]
Hi all

Because of the official release of aeroo reports for Odoo 8.0 is available - and after some tests I think it works nice, I will close all Issues here. Please use the official repository of alistek now: https://github.com/aeroo 

Thanks for all your help!
Kind Regards
Renzo

**Comment by raditv** [comment]
@rm-jamotion do you have Dockerfile sample for aero container?

**Comment by renzo1974** [comment]
Yes. Check this repo https://bitbucket.org/jamotion/aeroodocs/src

This image contains soffice and aerodocs running and will expose the port 8988.

The correspondig docker image is here https://bitbucket.org/jamotion/ansible-odoo/src. There is aeroolib installed.

**Comment by raditv** [comment]
@rm-jamotion ok, Thank you
